snyk python test

diff --git a/.github/workflows/sonar-snyk.yml b/.github/workflows/sonar-snyk.yml
--- a/.github/workflows/sonar-snyk.yml
+++ b/.github/workflows/sonar-snyk.yml
@@ -1,10 +1,6 @@
-name: Snyk Python Security Scan
+name: Python Security Scan with Snyk
 
-on:
-  push:
-    branches: [main]
-  pull_request:
-    branches: [main]
+on: push
 
 jobs:
   security:
@@ -12,28 +8,36 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.10'
+          python-version: 3.10
 
       - name: Install dependencies
+        run: pip install -r requirements.txt
+
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/python@master
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          command: code test
+          args: --sarif-file-output=snyk.sarif
+
+      - name: Count total number of vulnerabilities
         run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+          RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
+          echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
+          echo $RESULTS_LENGTH
 
-      - name: Snyk Test (Local Scan)
-        uses: snyk/actions/python@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          args: test
-
-      - name: Snyk Monitor (Send to Dashboard)
-        uses: snyk/actions/python@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-        with:
-          command: monitor
+      - name: Pass or Fail the Job
+        run: |
+          if [ "$RESULTS_LENGTH" != 0 ]; then
+              echo "Job Failed"
+              exit 1
+          else
+              echo "Pass"
+          fi
