snyk python test

diff --git a/.github/workflows/sonar-snyk.yml b/.github/workflows/sonar-snyk.yml
--- a/.github/workflows/sonar-snyk.yml
+++ b/.github/workflows/sonar-snyk.yml
@@ -1,43 +1,30 @@
-name: Python Security Scan with Snyk
-
+name: Example workflow for Python script scan using Snyk
 on: push
 
 jobs:
   security:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.10
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-
+      - uses: actions/checkout@master
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/python@master
-        continue-on-error: true
+        continue-on-error: true # To make sure that SARIF upload gets called
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: code test
           args: --sarif-file-output=snyk.sarif
-
+          
       - name: Count total number of vulnerabilities
         run: |
           RESULTS_LENGTH=$(jq '.runs[0].results | length' snyk.sarif)
           echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
           echo $RESULTS_LENGTH
-
-      - name: Pass or Fail the Job
+      - name: Pass_or_Fail_the_job
         run: |
-          if [ "$RESULTS_LENGTH" != 0 ]; then
-              echo "Job Failed"
-              exit 1
-          else
-              echo "Pass"
-          fi
+            if [ "$RESULTS_LENGTH" != 0 ]; then
+                echo "Job Failed"
+                exit 1
+            else
+                echo "Pass"
+            fi
